### ISSUE TITLE
Provide `destroy` destination (component) 

### ISSUE THREAD

**Issue by lukasborawski** [lukasborawski/vue-use-state-effect#2]
**Description**:
---
I would like to have an option to decide when I'm destroying the state (effect). 

**Requirements**:
* with a defined component (custom) name by property `stateEffect` I'll be able to pass it to the composable, 
* this will create dynamic value/property that would be managed directly from the component/page instance.

```typescript
const props = defineProps({
  stateEffect: { type: String, default: 'TestPage' },
})
```

**Tasks**:
---
- [x] provide possibility to pass `stateEffect` prop through the composable
- [x] destroy state effect on top of defined and passed component props
- [x] inform user if the property will be not provided/passed
- [x] write docs with explanation
- [x] add unit tests
- [x] cover the feature within the demos
- [x] add example component to the [StackBlitz](https://stackblitz.com/edit/vue-use-state-effect-demo) demo
- [x] release

**Research**:
---
None

**Screenshots**:
---
None
