### ISSUE TITLE
Provide possibility to pass additional data and handlers

### ISSUE THREAD

**Issue by lukasborawski** [lukasborawski/vue-use-state-effect#4]
**Description**:
---
I would like to pass additional data and handlers to the `UseStateEffect` composable.

**Tasks**:
---
- [x] add a possibility to pass add-ons to the state effect composable
- [x] cover with types
- [x] add unit tests
- [x] write documentation
- [x] cover this feature within the demos
- [x] add example component to the [StackBlitz](https://stackblitz.com/edit/vue-use-state-effect-demo) demo
- [x] release

**Research**:
---
Since `UseStateEffect` is using one instance of the Vue component that is already fired we can't initialize the second one inside the shared composable. It will not recognize the instance, because it will be outside of it. The reasonable solution here would be to pass some data and handlers through the composable options (`args`). It's already possible however, interface and out-detecting are not covered.

**Screenshots**:
---
*_None_*
